# defaults:
#   - models: 'resnet18'
# epochs: 3
# seed: 42
# log_interval: 10
# save_model: True
# save_interval: 1 # save model every 1 epoch
# num_workers: 4
defaults:
  - training.models: 'resnet18'
  - _self_
training:
  epochs: 5
  seed: 42
  log_interval: 10
  save_model: True
  save_interval: 1 # save model every 1 epoch
  num_workers: 4
system:
  wandb_project: 'dtu_mlops_02476'
  wandb_entity: 'metrics_logger'
  load_model_from: null
  file_name: 'models'
