steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/inference:latest', '-f', 'dockerfiles/predict.Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/inference:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'inference-server'
  - '--image'
  - 'gcr.io/$PROJECT_ID/inference:latest'
  - '--region'
  - 'europe-west1'
  - '--memory'
  - '3G'
  - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'gcr.io/$PROJECT_ID/inference:latest'
