steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/website:latest', '-f', 'dockerfiles/website.Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/website:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'website-server'
  - '--update-env-vars'
  - 'INFERENCE_API_URL=https://inference-server-ym6t3dqyaq-ew.a.run.app/predict'
  - '--image'
  - 'gcr.io/$PROJECT_ID/website:latest'
  - '--region'
  - 'europe-west1'
  - '--max-instances'
  - '3'
  - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'gcr.io/$PROJECT_ID/website:latest'
