name: "Run formatting and tests"

on:
  push:
    branches: '*' # [ main, feat-* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Verify formatting
      run: ruff src
    - name: Test with pytest
      run: pytest -v
